version: '3'

services:
  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - "8040:8040"
    command: gunicorn -w 1 -b 0.0.0.0:8040 wsgi:server

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
